language: c++

os: linux
dist: bionic
install: 
  - sudo apt-get install --yes libreadline7 cmake catch
compiler: g++

script: mkdir build && cd build && cmake -DCMAKE_VERBOSE_MAKEFILE=ON .. && make && ctest

after_success: 
  - cd ~/build/nbelakovski/cdb
  - bash <(curl -s https://codecov.io/bash)

